### ISSUE TITLE
Support import-values in chart dependencies

### ISSUE THREAD

**Issue by fstaudt** [fstaudt/helm-values#106]
Following syntax in Chart.yaml should be taken into account in generated JSON schema:
``` yaml
apiVersion: v2
version: 1.0.0
name: bundle
dependencies:
  - name: subchart
    version: 1.0.0
    import-values:
      - child: child-key
        parent: parent-key
```

Properties of child-key in subchart should be considered as valid when used in parent-key in bundle chart:
```yaml
# already valid
subchart:
  child-key:
    test: value
# should also be valid
parent-key:
  test: value
```

Short syntax for import-values in Chart.yaml should also be supported:
``` yaml
apiVersion: v2
version: 1.0.0
name: bundle
dependencies:
  - name: subchart
    version: 1.0.0
    import-values:
      - data
```

It should be treated as :
```yaml
dependencies:
  - name: subchart
    version: 1.0.0
    import-values:
      - child: exports.data
        parent: data
```
