### ISSUE TITLE
JSON schema extractor should take aliases into account

### ISSUE THREAD

**Issue by fstaudt** [fstaudt/helm-values#133]
When JSON schemas are extracted from dependencies, aliases used for sub-charts are ignored.

As a result, aggregated JSON schema incorrectly uses the chart name instead of the alias for the sub-charts.

### Example

dependent-chart/Chart.yaml:
``` yaml
apiVersion: v2
name: dependent-chart
version: 0.1.0
description: Dependent helm chart with alias in dependencies
dependencies:
  - name: sub-chart
    version: 0.1.0
    repository: "@thirdparty"
    alias: alias-chart
```

main-chart/Chart.yaml:
``` yaml
apiVersion: v2
name: main-chart
version: 0.1.0
description: Main helm chart
dependencies:
  - name: dependent-chart
    version: 0.1.0
    repository: "@thirdparty"
```

main-chart/values.yaml:
``` yaml
dependent-chart:
  sub-chart:             # is incorrectly documented and auto-completed
  alias-chart:           # is incorrectly considered as invalid
```
