### ISSUE TITLE
Refresh JSON schema fails when values contains a time

### ISSUE THREAD

**Issue by fstaudt** [fstaudt/helm-values#169]
When values.yaml of a dependency contains a time, e.g.:
```yaml
reconciliation:
  fromTime: 00:00:00.000
  toTime: 23:59:59.999
```

Refresh of JSON schemas for the chart fails with error:\
`Malformed numeric value '00:00:00.000' at [Source: (FileInputStream); line: 2, column: 24]`
