### ISSUE TITLE
aggregated schema of inter-dependent charts should be referenced when repository ends with /

### ISSUE THREAD

**Issue by fstaudt** [fstaudt/helm-values#52]
When repository contain inter-dependent charts, reference to aggregated schema is incorrect when path in repository ends with `/`.

``` yaml
# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "file://../nginx/"
```

Aggregated schema should contain following reference when generated by IntelliJ plugin:
``` json
{
  "$ref" : "../nginx/aggregated-values.schema.json"
}
```

It is currently incorrectly generated as:
``` json
{
  "$ref" : "..//aggregated-values.schema.json"
}
```
